# Generated by Django 6.0.2 on 2026-02-25 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CuttingOptimizationJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cad_file", models.FileField(upload_to="production/cad/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("stock_sheets", models.JSONField(blank=True, default=list)),
                ("extracted_parts", models.JSONField(blank=True, default=list)),
                ("optimization_result", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Cutting Optimization",
                "verbose_name_plural": "Cutting Optimization",
                "db_table": "prd_cutting_optimization",
            },
        ),
        migrations.CreateModel(
            name="ProductionOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order_no", models.CharField(max_length=50, unique=True)),
                ("planned_quantity", models.PositiveIntegerField(default=0)),
                ("produced_quantity", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Production Order",
                "verbose_name_plural": "Production Orders",
                "db_table": "prd_orders",
            },
        ),
        migrations.CreateModel(
            name="ProductionPlanning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "machine_loading_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("shift_schedule", models.JSONField(blank=True, default=list)),
                ("capacity_notes", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Production Planning",
                "verbose_name_plural": "Production Planning",
                "db_table": "prd_planning",
            },
        ),
        migrations.CreateModel(
            name="MachineIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "machine_type",
                    models.CharField(blank=True, default="CNC", max_length=60),
                ),
                ("machine_program", models.TextField(blank=True, default="")),
                (
                    "post_processor",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "production_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="machine_jobs",
                        to="production.productionorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Machine Integration",
                "verbose_name_plural": "Machine Integration",
                "db_table": "prd_machine_integration",
            },
        ),
        migrations.CreateModel(
            name="LaborTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("worker_name", models.CharField(max_length=120)),
                (
                    "shift_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "productivity_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "production_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="labor_logs",
                        to="production.productionorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Labor Tracking",
                "verbose_name_plural": "Labor Tracking",
                "db_table": "prd_labor_tracking",
            },
        ),
        migrations.CreateModel(
            name="BOMExplosion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("level", models.PositiveIntegerField(default=1)),
                ("component_code", models.CharField(max_length=100)),
                (
                    "required_quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "issued_quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "production_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bom_explosions",
                        to="production.productionorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "BOM Explosion",
                "verbose_name_plural": "BOM Explosion",
                "db_table": "prd_bom_explosion",
            },
        ),
        migrations.CreateModel(
            name="BatchTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("batch_no", models.CharField(max_length=80, unique=True)),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "production_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batches",
                        to="production.productionorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Batch Tracking",
                "verbose_name_plural": "Batch Tracking",
                "db_table": "prd_batch_tracking",
            },
        ),
        migrations.CreateModel(
            name="RejectionReworkManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rejected_quantity", models.PositiveIntegerField(default=0)),
                ("rework_quantity", models.PositiveIntegerField(default=0)),
                ("scrap_quantity", models.PositiveIntegerField(default=0)),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "production_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejections",
                        to="production.productionorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rejection & Rework Management",
                "verbose_name_plural": "Rejection & Rework Management",
                "db_table": "prd_rejection_rework",
            },
        ),
        migrations.CreateModel(
            name="ShopFloorControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "machine_code",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                ("bottleneck_flag", models.BooleanField(default=False)),
                (
                    "current_stage",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "progress_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "production_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_floor_updates",
                        to="production.productionorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shop Floor Control",
                "verbose_name_plural": "Shop Floor Control",
                "db_table": "prd_shop_floor",
            },
        ),
        migrations.CreateModel(
            name="SubcontractingManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("vendor_name", models.CharField(max_length=200)),
                ("vendor_work_order", models.CharField(max_length=80)),
                ("expected_return_date", models.DateField(blank=True, null=True)),
                (
                    "production_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subcontracting_jobs",
                        to="production.productionorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subcontracting Management",
                "verbose_name_plural": "Subcontracting Management",
                "db_table": "prd_subcontracting",
            },
        ),
        migrations.CreateModel(
            name="WIPTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stage_name", models.CharField(max_length=120)),
                ("stage_quantity", models.PositiveIntegerField(default=0)),
                (
                    "valuation",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "production_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wip_logs",
                        to="production.productionorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "WIP Tracking",
                "verbose_name_plural": "WIP Tracking",
                "db_table": "prd_wip_tracking",
            },
        ),
    ]
