# Generated by Django 6.0.2 on 2026-06-10 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0039_add_quote_attachment'),
        ('crm', '0016_alter_enquiry_status'),
        ('hrm', '0018_permit_and_remove_employee_permits_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(blank=True, editable=False, max_length=30, unique=True, verbose_name='job number')),
                ('project_name', models.CharField(max_length=255, verbose_name='project name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('location', models.CharField(blank=True, default='', max_length=500, verbose_name='location')),
                ('status', models.CharField(choices=[('quotation_approved', 'Quotation Approved'), ('planning', 'Planning'), ('in_production', 'In Production'), ('quality_check', 'Quality Check'), ('ready_for_delivery', 'Ready for Delivery'), ('delivery_in_progress', 'Delivery in Progress'), ('installation', 'Installation'), ('installation_completed', 'Installation Completed'), ('snagging', 'Snagging'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='quotation_approved', max_length=30, verbose_name='status')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='actual end date')),
                ('contract_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='contract value')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='assessment.boq')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='crm.customer')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
                ('quote', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='assessment.quote')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_project', models.CharField(choices=[('project_manager', 'Project Manager'), ('site_supervisor', 'Site Supervisor'), ('lead_carpenter', 'Lead Carpenter'), ('carpenter', 'Carpenter'), ('painter', 'Painter'), ('electrician', 'Electrician'), ('logistics', 'Logistics Coordinator'), ('qa_inspector', 'QA Inspector'), ('installer', 'Installer'), ('designer', 'Designer'), ('draftsman', 'Draftsman'), ('procurement', 'Procurement Officer'), ('other', 'Other')], default='other', max_length=25, verbose_name='role in project')),
                ('custom_role', models.CharField(blank=True, default='', help_text="Used when role_in_project = 'other'.", max_length=100, verbose_name='custom role')),
                ('allocated_from', models.DateField(blank=True, null=True, verbose_name='allocated from')),
                ('allocated_to', models.DateField(blank=True, null=True, verbose_name='allocated to')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('allocation_pct', models.PositiveSmallIntegerField(default=100, help_text='Percentage of working time allocated to this project.', verbose_name='allocation %')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_project_team_members', to=settings.AUTH_USER_MODEL)),
                ('designation', models.ForeignKey(blank=True, help_text="Auto-filled from employee's HRM designation; can be overridden.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_team_members', to='hrm.designation')),
                ('employee', models.ForeignKey(help_text='Select from the HRM employee roster.', on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='hrm.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='Projects.project')),
            ],
            options={
                'verbose_name': 'project team member',
                'verbose_name_plural': 'project team members',
                'ordering': ['role_in_project', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('project', 'employee'), name='uniq_project_employee')],
            },
        ),
    ]
