# Generated by Django 6.0.2 on 2026-06-09 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmaterial",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="allocated_materials", to="Projects.project"
            ),
        ),
        migrations.CreateModel(
            name="Labour",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sl_no", models.PositiveIntegerField(verbose_name="serial number")),
                ("designation", models.CharField(max_length=255, verbose_name="designation")),
                ("category", models.CharField(max_length=255, verbose_name="category")),
                ("hrs", models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name="hours")),
                ("rate", models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="rate")),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="amount")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="labours", to="Projects.project"
                    ),
                ),
            ],
            options={
                "verbose_name": "estimate labour",
                "verbose_name_plural": "estimate labours",
                "ordering": ["sl_no"],
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("item", models.CharField(max_length=255, verbose_name="item")),
                ("material", models.CharField(max_length=255, verbose_name="material")),
                ("unit", models.CharField(max_length=50, verbose_name="unit")),
                (
                    "stock_in_hand",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name="stock in hand"),
                ),
                (
                    "req_qty",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name="required quantity"),
                ),
                ("notes_remarks", models.TextField(blank=True, default="", verbose_name="notes / remarks")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="materials", to="Projects.project"
                    ),
                ),
            ],
            options={
                "verbose_name": "estimate material",
                "verbose_name_plural": "estimate materials",
                "ordering": ["item", "material"],
            },
        ),
        migrations.CreateModel(
            name="Other",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("item_description", models.CharField(max_length=255, verbose_name="item description")),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="amount")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="others", to="Projects.project"
                    ),
                ),
            ],
            options={
                "verbose_name": "estimate other cost",
                "verbose_name_plural": "estimate other costs",
                "ordering": ["item_description"],
            },
        ),
    ]
