# Generated by Django 6.0.2 on 2026-06-10

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


def forwards_populate_material_relations(apps, schema_editor):
    Material = apps.get_model("Projects", "Material")
    QuoteItem = apps.get_model("assessment", "QuoteItem")
    Product = apps.get_model("inventory", "Product")

    for row in Material.objects.all().iterator():
        if row.item:
            row.item_fk = QuoteItem.objects.filter(name=row.item).first()
        if row.material:
            row.material_fk = Product.objects.filter(
                Q(name=row.material) | Q(sku=row.material) | Q(product_code=row.material)
            ).first()
        row.save(update_fields=["item_fk", "material_fk"])


def reverse_populate_material_relations(apps, schema_editor):
    # Historical string values are not recoverable from the FK-only state.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("Projects", "0002_estimate_models"),
        ("assessment", "0039_add_quote_attachment"),
        ("inventory", "0049_sync_product_stock_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="item_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="estimate_materials",
                to="assessment.quoteitem",
                verbose_name="item",
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="material_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="estimate_materials",
                to="inventory.product",
                verbose_name="material",
            ),
        ),
        migrations.RunPython(forwards_populate_material_relations, reverse_populate_material_relations),
        migrations.RemoveField(
            model_name="material",
            name="item",
        ),
        migrations.RemoveField(
            model_name="material",
            name="material",
        ),
        migrations.RenameField(
            model_name="material",
            old_name="item_fk",
            new_name="item",
        ),
        migrations.RenameField(
            model_name="material",
            old_name="material_fk",
            new_name="material",
        ),
    ]
