# Generated by Django 6.0.2 on 2026-06-10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Projects", "0003_alter_material_item_and_material"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="material",
            name="stock_in_hand",
        ),
    ]
