# Generated by Django 6.0.2 on 2026-06-10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Projects", "0004_remove_material_stock_in_hand"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="material",
            name="unit",
        ),
    ]
