# Generated by Django 6.0.2 on 2026-06-10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Projects", "0005_remove_material_unit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="labour",
            name="sl_no",
        ),
    ]
