# Generated by Django 6.0.2 on 2026-06-10

import django.db.models.deletion
from django.db import migrations, models


def forwards_add_designation_fk_column(apps, schema_editor):
    table_name = "Projects_labour"
    column_name = "designation_fk_id"
    with schema_editor.connection.cursor() as cursor:
        existing_columns = {
            column.name for column in schema_editor.connection.introspection.get_table_description(cursor, table_name)
        }
    if column_name not in existing_columns:
        schema_editor.execute(f"ALTER TABLE `{table_name}` ADD COLUMN `{column_name}` bigint NULL")


def forwards_populate_labour_designation(apps, schema_editor):
    table_name = "Projects_labour"
    designation_table = "hrm_designation"
    schema_editor.execute(
        f"""
        UPDATE `{table_name}` l
        INNER JOIN `{designation_table}` d
            ON LOWER(d.`name`) = LOWER(l.`designation`)
        SET l.`designation_fk_id` = d.`id`
        """
    )


def forwards_remove_old_designation_column(apps, schema_editor):
    table_name = "Projects_labour"
    column_name = "designation"
    with schema_editor.connection.cursor() as cursor:
        existing_columns = {
            column.name for column in schema_editor.connection.introspection.get_table_description(cursor, table_name)
        }
    if column_name in existing_columns:
        schema_editor.execute(f"ALTER TABLE `{table_name}` DROP COLUMN `{column_name}`")


def forwards_rename_designation_fk_column(apps, schema_editor):
    table_name = "Projects_labour"
    old_name = "designation_fk_id"
    new_name = "designation_id"
    with schema_editor.connection.cursor() as cursor:
        existing_columns = {
            column.name for column in schema_editor.connection.introspection.get_table_description(cursor, table_name)
        }
    if old_name in existing_columns and new_name not in existing_columns:
        schema_editor.execute(f"ALTER TABLE `{table_name}` RENAME COLUMN `{old_name}` TO `{new_name}`")


def reverse_populate_labour_designation(apps, schema_editor):
    # Text values cannot be reconstructed perfectly from FK-only data.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("Projects", "0007_remove_labour_category"),
        ("hrm", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(forwards_add_designation_fk_column, migrations.RunPython.noop),
                migrations.RunPython(forwards_populate_labour_designation, reverse_populate_labour_designation),
                migrations.RunPython(forwards_remove_old_designation_column, migrations.RunPython.noop),
                migrations.RunPython(forwards_rename_designation_fk_column, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="labour",
                    name="designation_fk",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estimate_labours",
                        to="hrm.designation",
                        verbose_name="designation",
                    ),
                ),
                migrations.RemoveField(
                    model_name="labour",
                    name="designation",
                ),
                migrations.RenameField(
                    model_name="labour",
                    old_name="designation_fk",
                    new_name="designation",
                ),
            ],
        ),
    ]
