# Generated by Django 6.0.2 on 2026-02-18 10:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrm", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={
                "ordering": ["-date", "-check_in"],
                "verbose_name": "attendance",
                "verbose_name_plural": "attendances",
            },
        ),
        migrations.AlterModelOptions(
            name="department",
            options={"ordering": ["-created_at"], "verbose_name": "department", "verbose_name_plural": "departments"},
        ),
        migrations.AlterModelOptions(
            name="designation",
            options={"ordering": ["-created_at"], "verbose_name": "designation", "verbose_name_plural": "designations"},
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={"ordering": ["-created_at"], "verbose_name": "employee", "verbose_name_plural": "employees"},
        ),
        migrations.AddField(
            model_name="attendance",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="department",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="department",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="is active"),
        ),
        migrations.AddField(
            model_name="designation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="designation",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="is active"),
        ),
        migrations.AddField(
            model_name="employee",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="hrm.department",
                verbose_name="department",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="designation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="hrm.designation",
                verbose_name="designation",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="is active"),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="check_in",
            field=models.TimeField(blank=True, null=True, verbose_name="check in"),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="check_out",
            field=models.TimeField(blank=True, null=True, verbose_name="check out"),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(verbose_name="date"),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="hrm.employee",
                verbose_name="employee",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(max_length=50, verbose_name="status"),
        ),
        migrations.AlterField(
            model_name="department",
            name="code",
            field=models.CharField(max_length=50, unique=True, verbose_name="code"),
        ),
        migrations.AlterField(
            model_name="department",
            name="head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_departments",
                to="hrm.employee",
                verbose_name="head",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="designation",
            name="code",
            field=models.CharField(max_length=50, unique=True, verbose_name="code"),
        ),
        migrations.AlterField(
            model_name="designation",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="designations",
                to="hrm.department",
                verbose_name="department",
            ),
        ),
        migrations.AlterField(
            model_name="designation",
            name="head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_designations",
                to="hrm.employee",
                verbose_name="head",
            ),
        ),
        migrations.AlterField(
            model_name="designation",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="email address"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="last name"),
        ),
    ]
