# Generated by Django 6.0.2 on 2026-02-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrm", "0003_leavetype_leaverequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="code",
        ),
        migrations.AddField(
            model_name="department",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="name"),
        ),
    ]
