# Generated by Django 6.0.2 on 2026-02-19 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_companyfeature'),
        ('hrm', '0006_employee_user_alter_employee_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='company.company'),
        ),
    ]
