# Generated by Django 6.0.2 on 2026-02-19 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0007_employee_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='access_card_allocated',
            field=models.BooleanField(default=False, verbose_name='access card allocated'),
        ),
        migrations.AddField(
            model_name='employee',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='account number'),
        ),
        migrations.AddField(
            model_name='employee',
            name='allergies',
            field=models.TextField(blank=True, null=True, verbose_name='allergies'),
        ),
        migrations.AddField(
            model_name='employee',
            name='attestation_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='attestation status'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='bank name'),
        ),
        migrations.AddField(
            model_name='employee',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='basic salary'),
        ),
        migrations.AddField(
            model_name='employee',
            name='biometric_registration_done',
            field=models.BooleanField(default=False, verbose_name='biometric registration done'),
        ),
        migrations.AddField(
            model_name='employee',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='blood group'),
        ),
        migrations.AddField(
            model_name='employee',
            name='certifications',
            field=models.JSONField(blank=True, default=list, verbose_name='certifications'),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('MOHRE Standard Fixed-Term', 'MOHRE Standard Fixed-Term')], max_length=100, null=True, verbose_name='contract type'),
        ),
        migrations.AddField(
            model_name='employee',
            name='current_address_uae',
            field=models.TextField(blank=True, null=True, verbose_name='current address UAE'),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True, verbose_name='date of joining'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_home_country_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='home country phone'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='emergency contact name'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='emergency contact phone'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='relationship'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emirates_id_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Emirates ID expiry date'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emirates_id_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Emirates ID number'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_signature',
            field=models.ImageField(blank=True, null=True, upload_to='employees/signatures/', verbose_name='employee signature'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Limited Contract', 'Limited Contract')], max_length=50, null=True, verbose_name='employment type'),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='employee',
            name='highest_qualification',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='highest qualification'),
        ),
        migrations.AddField(
            model_name='employee',
            name='housing_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='housing allowance'),
        ),
        migrations.AddField(
            model_name='employee',
            name='hr_signature',
            field=models.ImageField(blank=True, null=True, upload_to='employees/signatures/', verbose_name='HR signature'),
        ),
        migrations.AddField(
            model_name='employee',
            name='iban_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IBAN number'),
        ),
        migrations.AddField(
            model_name='employee',
            name='institution_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='institution name'),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='job title'),
        ),
        migrations.AddField(
            model_name='employee',
            name='labor_card_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='labor card number'),
        ),
        migrations.AddField(
            model_name='employee',
            name='laptop_allocated',
            field=models.BooleanField(default=False, verbose_name='laptop allocated'),
        ),
        migrations.AddField(
            model_name='employee',
            name='medical_conditions',
            field=models.TextField(blank=True, null=True, verbose_name='medical conditions'),
        ),
        migrations.AddField(
            model_name='employee',
            name='medical_insurance_provider',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='medical insurance provider'),
        ),
        migrations.AddField(
            model_name='employee',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='mobile number'),
        ),
        migrations.AddField(
            model_name='employee',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='nationality'),
        ),
        migrations.AddField(
            model_name='employee',
            name='offer_letter_reference_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='offer letter reference'),
        ),
        migrations.AddField(
            model_name='employee',
            name='other_allowances',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='other allowances'),
        ),
        migrations.AddField(
            model_name='employee',
            name='overtime_eligible',
            field=models.BooleanField(default=True, verbose_name='overtime eligible'),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='passport expiry date'),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='passport issue date'),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='passport number'),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_place_of_issue',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='place of issue'),
        ),
        migrations.AddField(
            model_name='employee',
            name='permanent_address_home_country',
            field=models.TextField(blank=True, null=True, verbose_name='permanent address home country'),
        ),
        migrations.AddField(
            model_name='employee',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='personal email'),
        ),
        migrations.AddField(
            model_name='employee',
            name='policy_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='policy number'),
        ),
        migrations.AddField(
            model_name='employee',
            name='probation_period_months',
            field=models.IntegerField(blank=True, default=6, null=True, verbose_name='probation period (months)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='employees/photos/', verbose_name='profile photo'),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_payment_cycle',
            field=models.CharField(default='Monthly', max_length=50, verbose_name='salary payment cycle'),
        ),
        migrations.AddField(
            model_name='employee',
            name='signature_date',
            field=models.DateField(blank=True, null=True, verbose_name='signature date'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sim_card_allocated',
            field=models.BooleanField(default=False, verbose_name='SIM card allocated'),
        ),
        migrations.AddField(
            model_name='employee',
            name='total_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total salary'),
        ),
        migrations.AddField(
            model_name='employee',
            name='transport_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='transport allowance'),
        ),
        migrations.AddField(
            model_name='employee',
            name='uae_visa_type',
            field=models.CharField(blank=True, choices=[('Employment', 'Employment'), ('Mission', 'Mission'), ('Tourist-to-Work', 'Tourist-to-Work')], max_length=50, null=True, verbose_name='UAE visa type'),
        ),
        migrations.AddField(
            model_name='employee',
            name='uid_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UID number'),
        ),
        migrations.AddField(
            model_name='employee',
            name='visa_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='visa expiry date'),
        ),
        migrations.AddField(
            model_name='employee',
            name='visa_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='visa issue date'),
        ),
        migrations.AddField(
            model_name='employee',
            name='visa_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='visa number'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_location',
            field=models.CharField(blank=True, choices=[('Factory', 'Factory'), ('Showroom', 'Showroom'), ('Office', 'Office')], max_length=50, null=True, verbose_name='work location'),
        ),
        migrations.AddField(
            model_name='employee',
            name='working_days',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='working days'),
        ),
        migrations.AddField(
            model_name='employee',
            name='working_hours',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='working hours'),
        ),
        migrations.AddField(
            model_name='employee',
            name='year_of_graduation',
            field=models.IntegerField(blank=True, null=True, verbose_name='year of graduation'),
        ),
        migrations.CreateModel(
            name='PreviousEmployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='company name')),
                ('designation', models.CharField(max_length=100, verbose_name='designation')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('reason_for_leaving', models.TextField(blank=True, null=True, verbose_name='reason for leaving')),
                ('experience_certificate_attached', models.BooleanField(default=False, verbose_name='experience certificate attached')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_employments', to='hrm.employee', verbose_name='employee')),
            ],
            options={
                'verbose_name': 'previous employment',
                'verbose_name_plural': 'previous employments',
            },
        ),
    ]
