# Generated by Django 6.0.2 on 2026-02-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0008_employee_access_card_allocated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='personal_email',
        ),
        migrations.AlterField(
            model_name='employee',
            name='uae_visa_type',
            field=models.CharField(blank=True, choices=[('Golden Visa', 'Golden Visa (5 or 10 years)'), ('Green Visa', 'Green Visa (5 years)'), ('Residence Visa', 'Residence Visa (2 years)'), ('Tourist Visa', 'Tourist Visa'), ('Transit Visa', 'Transit Visa (48/96 hours)'), ('Remote Work', 'Remote Work/Virtual Visa'), ('Retirement Visa', 'Retirement Visa (5 years)')], max_length=50, null=True, verbose_name='UAE visa type'),
        ),
    ]
