# Generated by Django 6.0.2 on 2026-02-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrm", "0011_alter_employee_uae_visa_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="contract_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MOHRE_Fixed_Term", "MOHRE Standard Fixed-Term"),
                    ("MOHRE_Part_Time", "MOHRE Part-Time Contract"),
                    ("MOHRE_Temporary", "MOHRE Temporary Contract"),
                    ("MOHRE_Flexible", "MOHRE Flexible Contract"),
                    ("MOHRE_Job_Share", "MOHRE Job Sharing Contract"),
                    ("MOHRE_Remote", "MOHRE Remote Work Contract"),
                    ("Freezone_Standard", "Free Zone Employment Contract"),
                    ("Freezone_Fixed", "Free Zone Fixed-Term Contract"),
                    ("Limited", "Limited Contract (Legacy)"),
                    ("Unlimited", "Unlimited Contract (Legacy)"),
                    ("Probation", "Probationary Contract"),
                    ("Consultancy", "Consultancy / Service Contract"),
                    ("Internship", "Internship / Training Contract"),
                ],
                max_length=100,
                null=True,
                verbose_name="contract type",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="employment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Full_Time", "Full-time"),
                    ("Part_Time", "Part-time"),
                    ("Temporary", "Temporary"),
                    ("Flexible", "Flexible Working"),
                    ("Remote", "Remote Work"),
                    ("Job_Share", "Job Sharing"),
                ],
                max_length=50,
                null=True,
                verbose_name="employment type",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="uae_visa_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Tourist_30_Single", "Tourist Visa - 30 Days (Single Entry)"),
                    ("Tourist_30_Multi", "Tourist Visa - 30 Days (Multiple Entry)"),
                    ("Tourist_60_Single", "Tourist Visa - 60 Days (Single Entry)"),
                    ("Tourist_60_Multi", "Tourist Visa - 60 Days (Multiple Entry)"),
                    ("Tourist_5_Year_Multi", "5-Year Multiple Entry Tourist Visa"),
                    ("Transit_48", "Transit Visa - 48 Hours"),
                    ("Transit_96", "Transit Visa - 96 Hours"),
                    ("Visit_Family", "Visit Visa for Family/Friends"),
                    ("Visa_On_Arrival", "Visa on Arrival"),
                    ("Employment", "Employment Visa (Work Visa)"),
                    ("Investor", "Investor Visa"),
                    ("Partner", "Partner Visa"),
                    ("Freelancer", "Freelancer Visa"),
                    ("Remote_Work", "Remote Work Visa"),
                    ("Green", "Green Visa"),
                    ("Golden", "Golden Visa"),
                    ("Property_Owner", "Property Owner Visa"),
                    ("Retirement", "Retirement Visa"),
                    ("Student", "Student Visa"),
                    ("Dependent", "Dependent Visa (Spouse/Children/Parents)"),
                    ("Domestic_Worker", "Domestic Worker Visa"),
                    ("Medical", "Medical Treatment Visa"),
                    ("Patient_Companion", "Patient Companion Visa"),
                    ("Conference", "Conference / Event Visa"),
                    ("Mission", "Mission Visa (Short-term Work Permit)"),
                    ("Crew", "Crew Visa"),
                ],
                max_length=50,
                null=True,
                verbose_name="UAE visa type",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="work_location",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Factory", "Factory"),
                    ("Showroom", "Showroom"),
                    ("Office", "Office"),
                    ("Site", "Site"),
                    ("Warehouse", "Warehouse"),
                    ("Other", "Other"),
                ],
                max_length=50,
                null=True,
                verbose_name="work location",
            ),
        ),
    ]
