# Generated by Django 6.0.2 on 2026-02-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0012_alter_employee_contract_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('MOHRE_FIXED_TERM', 'MOHRE Standard Fixed-Term'), ('MOHRE_PART_TIME', 'MOHRE Part-Time Contract'), ('MOHRE_TEMPORARY', 'MOHRE Temporary Contract'), ('MOHRE_FLEXIBLE', 'MOHRE Flexible Contract'), ('MOHRE_JOB_SHARE', 'MOHRE Job Sharing Contract'), ('MOHRE_REMOTE', 'MOHRE Remote Work Contract'), ('FREEZONE_STANDARD', 'Free Zone Employment Contract'), ('FREEZONE_FIXED', 'Free Zone Fixed-Term Contract'), ('LIMITED', 'Limited Contract (Legacy)'), ('UNLIMITED', 'Unlimited Contract (Legacy)'), ('PROBATION', 'Probationary Contract'), ('CONSULTANCY', 'Consultancy / Service Contract'), ('INTERNSHIP', 'Internship / Training Contract')], max_length=100, null=True, verbose_name='contract type'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('FULL_TIME', 'Full-time'), ('PART_TIME', 'Part-time'), ('TEMPORARY', 'Temporary'), ('FLEXIBLE', 'Flexible Working'), ('REMOTE', 'Remote Work'), ('JOB_SHARE', 'Job Sharing')], max_length=50, null=True, verbose_name='employment type'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='uae_visa_type',
            field=models.CharField(blank=True, choices=[('TOURIST_30_SINGLE', 'Tourist Visa - 30 Days (Single Entry)'), ('TOURIST_30_MULTI', 'Tourist Visa - 30 Days (Multiple Entry)'), ('TOURIST_60_SINGLE', 'Tourist Visa - 60 Days (Single Entry)'), ('TOURIST_60_MULTI', 'Tourist Visa - 60 Days (Multiple Entry)'), ('TOURIST_5_YEAR_MULTI', '5-Year Multiple Entry Tourist Visa'), ('TRANSIT_48', 'Transit Visa - 48 Hours'), ('TRANSIT_96', 'Transit Visa - 96 Hours'), ('VISIT_FAMILY', 'Visit Visa for Family/Friends'), ('VISA_ON_ARRIVAL', 'Visa on Arrival'), ('EMPLOYMENT', 'Employment Visa (Work Visa)'), ('INVESTOR', 'Investor Visa'), ('PARTNER', 'Partner Visa'), ('FREELANCER', 'Freelancer Visa'), ('REMOTE_WORK', 'Remote Work Visa'), ('GREEN', 'Green Visa'), ('GOLDEN', 'Golden Visa'), ('PROPERTY_OWNER', 'Property Owner Visa'), ('RETIREMENT', 'Retirement Visa'), ('STUDENT', 'Student Visa'), ('DEPENDENT', 'Dependent Visa (Spouse/Children/Parents)'), ('DOMESTIC_WORKER', 'Domestic Worker Visa'), ('MEDICAL', 'Medical Treatment Visa'), ('PATIENT_COMPANION', 'Patient Companion Visa'), ('CONFERENCE', 'Conference / Event Visa'), ('MISSION', 'Mission Visa (Short-term Work Permit)'), ('CREW', 'Crew Visa')], max_length=50, null=True, verbose_name='UAE visa type'),
        ),
    ]
