# Generated by Django 6.0.2 on 2026-02-20 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0013_alter_employee_contract_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='job_title',
        ),
    ]
