# Generated by Django 6.0.2 on 2026-03-17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boq",
            name="description",
        ),
        migrations.RemoveField(
            model_name="boq",
            name="title",
        ),
        migrations.RemoveField(
            model_name="boq",
            name="total_amount",
        ),
    ]
