# Generated by Django 6.0.2 on 2026-03-17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0002_remove_boq_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boq",
            name="attachment",
        ),
    ]
