# Generated by Django 6.0.2 on 2026-03-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0003_remove_boq_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="boqitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=14,
                verbose_name="unit price",
            ),
        ),
        migrations.AddField(
            model_name="boqitem",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=14,
                verbose_name="amount",
            ),
        ),
    ]
