# Generated by Django 6.0.2 on 2026-03-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0004_add_boqitem_prices"),
    ]

    operations = [
        migrations.AddField(
            model_name="boq",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="is approved"),
        ),
        migrations.AddField(
            model_name="boq",
            name="is_rejected",
            field=models.BooleanField(default=False, verbose_name="is rejected"),
        ),
    ]
