# Generated by Django 6.0.2 on 2026-03-23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0005_add_boq_flags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boqitem",
            name="unit_price",
        ),
        migrations.RemoveField(
            model_name="boqitem",
            name="amount",
        ),
    ]
