# Generated by Django 6.0.2 on 2026-03-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0008_add_quote_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="quote_number",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="quote number",
            ),
        ),
    ]
