# Generated by Django 6.0.2 on 2026-03-23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0009_add_quote_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Finish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("finish_name", models.CharField(max_length=200, verbose_name="finish name")),
                ("finish_type", models.CharField(max_length=150, verbose_name="finish type")),
                ("material", models.CharField(max_length=200, verbose_name="material")),
                (
                    "finish_height",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=14,
                        verbose_name="finish height",
                    ),
                ),
                (
                    "finish_width",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=14,
                        verbose_name="finish width",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finishes",
                        to="assessment.quote",
                        verbose_name="quote",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuoteItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="assessment/quote_items/",
                        verbose_name="image",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "width",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name="width"),
                ),
                (
                    "height",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name="height"),
                ),
                (
                    "depth",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name="depth"),
                ),
                ("accessories", models.TextField(blank=True, verbose_name="accessories")),
                ("category", models.CharField(blank=True, max_length=100, verbose_name="category")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=14,
                        verbose_name="quantity",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="unit price",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name="amount"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "boq_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quote_items",
                        to="assessment.boqitem",
                        verbose_name="boq item",
                    ),
                ),
                (
                    "finishes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quote_items",
                        to="assessment.finish",
                        verbose_name="finishes",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="assessment.quote",
                        verbose_name="quote",
                    ),
                ),
            ],
        ),
    ]
