# Generated by Django 6.0.2 on 2026-03-23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0010_finish_quoteitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="finish",
            name="quote_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="finishes",
                to="assessment.quoteitem",
                verbose_name="quote item",
            ),
        ),
        migrations.RemoveField(
            model_name="finish",
            name="quote",
        ),
        migrations.AlterField(
            model_name="finish",
            name="quote_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="finishes",
                to="assessment.quoteitem",
                verbose_name="quote item",
            ),
        ),
        migrations.RemoveField(
            model_name="quoteitem",
            name="finishes",
        ),
    ]
