# Generated by Django 6.0.2 on 2026-03-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0011_finish_quote_item_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=14,
                verbose_name="total amount",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="total_items",
            field=models.PositiveIntegerField(default=0, verbose_name="total items"),
        ),
    ]
