# Generated by Django 6.0.2 on 2026-03-26 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0013_term"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="finish",
            name="finish_height",
        ),
        migrations.RemoveField(
            model_name="finish",
            name="finish_width",
        ),
    ]
