# Generated by Django 6.0.2 on 2026-03-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0014_remove_finish_finish_height_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="finish",
            name="design",
            field=models.CharField(blank=True, max_length=200, verbose_name="design"),
        ),
    ]
