# Generated by Django 6.0.2 on 2026-03-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0015_finish_design"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finish",
            name="design",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="design"
            ),
        ),
        migrations.AlterField(
            model_name="finish",
            name="finish_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="finish name"
            ),
        ),
        migrations.AlterField(
            model_name="finish",
            name="finish_type",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="finish type"
            ),
        ),
        migrations.AlterField(
            model_name="finish",
            name="material",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="material"
            ),
        ),
    ]
