# Generated by Django 6.0.2 on 2026-03-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0016_alter_finish_design_alter_finish_finish_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="finish",
            name="instance_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                verbose_name="instance price",
            ),
        ),
        migrations.AddField(
            model_name="finish",
            name="unit",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="unit"
            ),
        ),
    ]
