# Generated by Django 6.0.2 on 2026-03-28 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0017_finish_instance_price_finish_unit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="finish",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="finish",
            name="updated_at",
        ),
    ]
