# Generated by Django 6.0.2 on 2026-03-28 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0018_remove_finish_created_at_remove_finish_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                ("category", models.CharField(max_length=100, verbose_name="category")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "template",
                "verbose_name_plural": "templates",
            },
        ),
        migrations.CreateModel(
            name="TemplateFinish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "finish_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="finish name",
                    ),
                ),
                (
                    "finish_type",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="finish type",
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="material"
                    ),
                ),
                (
                    "design",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="design"
                    ),
                ),
                (
                    "instance_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="instance price",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="unit"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finishes",
                        to="assessment.template",
                        verbose_name="template",
                    ),
                ),
            ],
            options={
                "verbose_name": "template finish",
                "verbose_name_plural": "template finishes",
            },
        ),
    ]
