# Generated by Django 6.0.2 on 2026-03-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0019_template_templatefinish"),
    ]

    operations = [
        migrations.RenameField(
            model_name="finish",
            old_name="instance_price",
            new_name="unit_price",
        ),
        migrations.RenameField(
            model_name="templatefinish",
            old_name="instance_price",
            new_name="unit_price",
        ),
    ]
