# Generated by Django 6.0.2 on 2026-03-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0020_remove_finish_instance_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finish",
            name="unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                verbose_name="unit price",
            ),
        ),
        migrations.AlterField(
            model_name="templatefinish",
            name="unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                verbose_name="unit price",
            ),
        ),
    ]
