# Generated by Django 6.0.2 on 2026-03-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0021_rename_instance_price_verbose_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="finish",
            name="quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="quantity",
            ),
        ),
        migrations.AddField(
            model_name="finish",
            name="total_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                verbose_name="total price",
            ),
        ),
        migrations.AddField(
            model_name="templatefinish",
            name="quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="quantity",
            ),
        ),
        migrations.AddField(
            model_name="templatefinish",
            name="total_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                verbose_name="total price",
            ),
        ),
    ]
