# Generated by Django 6.0.2 on 2026-03-28 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0022_add_quantity_total_price_to_finishes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="templatefinish",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="templatefinish",
            name="total_price",
        ),
    ]
