# Generated by Django 6.0.2 on 2026-03-28 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0023_remove_quantity_total_price_from_template_finish"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Term",
            new_name="QuoteTermsConditions",
        ),
        migrations.RemoveField(
            model_name="QuoteTermsConditions",
            name="is_default",
        ),
        migrations.RemoveField(
            model_name="QuoteTermsConditions",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="QuoteTermsConditions",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="QuoteTermsConditions",
            name="quote",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="terms_conditions",
                to="assessment.quote",
                verbose_name="quote",
            ),
        ),
    ]
