# Generated by Django 6.0.2 on 2026-03-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0024_remove_fields_from_quote_terms_conditions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boq',
            options={'ordering': ['-created_at'], 'verbose_name': 'boq', 'verbose_name_plural': 'boqs'},
        ),
        migrations.AlterModelOptions(
            name='boqitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'boq item', 'verbose_name_plural': 'boq items'},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['-created_at'], 'verbose_name': 'quote', 'verbose_name_plural': 'quotes'},
        ),
        migrations.AddField(
            model_name='boq',
            name='status',
            field=models.CharField(default='Awaiting BOQ', max_length=50, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(default='awaiting quotation', max_length=50, verbose_name='status'),
        ),
    ]
