# Generated by Django 6.0.2 on 2026-03-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0025_alter_boq_options_alter_boqitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finish',
            name='template',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='template'),
        ),
    ]
