# Generated by Django 6.0.2 on 2026-03-30 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0026_finish_template"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quotetermsconditions",
            options={
                "ordering": ["id"],
                "verbose_name": "quote terms conditions",
                "verbose_name_plural": "quote terms conditions",
            },
        ),
    ]
