# Generated by Django 6.0.2 on 2026-03-31 15:45

from django.db import migrations


def drop_quote_financial_columns_if_exists(apps, schema_editor):
    table_name = "assessment_quote"
    columns_to_drop = {"discount_amount", "vat_percent", "total"}

    with schema_editor.connection.cursor() as cursor:
        existing_columns = {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(cursor, table_name)
        }

    for column_name in columns_to_drop:
        if column_name in existing_columns:
            schema_editor.execute(
                f"ALTER TABLE {schema_editor.quote_name(table_name)} "
                f"DROP COLUMN {schema_editor.quote_name(column_name)}"
            )


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0031_add_quote_approval_audit_fields"),
    ]

    operations = [
        migrations.RunPython(drop_quote_financial_columns_if_exists, migrations.RunPython.noop),
    ]
