# Generated by Django 6.0.2 on 2026-03-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0032_remove_quote_financial_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name="discount amount"),
        ),
        migrations.AddField(
            model_name="quote",
            name="exclusive_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name="exclusive total"),
        ),
        migrations.AddField(
            model_name="quote",
            name="grand_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name="grand total"),
        ),
        migrations.AddField(
            model_name="quote",
            name="vat_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name="vat amount"),
        ),
        migrations.AddField(
            model_name="quote",
            name="vat_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name="vat percent"),
        ),
    ]
