# Generated by Django 6.0.2 on 2026-04-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0033_add_quote_financial_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="client_status",
            field=models.CharField(
                blank=True,
                choices=[("accepted", "Accepted"), ("rejected", "Rejected")],
                max_length=20,
                null=True,
                verbose_name="client status",
            ),
        ),
    ]
