# Generated by Django 6.0.2 on 2026-04-23 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0037_quoteitem_accessories_fk_refactor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quoteitem",
            name="sku",
        ),
    ]
