$kind: http-request
method: POST
url: '{{baseUrl}}/api/v1/inventory/finishes/'
order: 56000
headers:
  - key: Accept
    value: application/json
  - key: Content-Type
    value: application/json
auth:
  type: bearer
  credentials:
    - key: token
      value: '{{AccessToken}}'
body:
  type: json
  content: |-
    {
      "name": "Example Finish",
      "code": "EXFN"
    }
