$kind: http-request
method: GET
url: '{{baseUrl}}/api/v1/inventory/products/'
order: 58000
headers:
  - key: Accept
    value: application/json
auth:
  type: bearer
  credentials:
    - key: token
      value: '{{AccessToken}}'
