$kind: http-request
method: POST
url: '{{baseUrl}}/api/v1/inventory/products/'
order: 59000
headers:
  - key: Accept
    value: application/json
  - key: Content-Type
    value: application/json
auth:
  type: bearer
  credentials:
    - key: token
      value: '{{AccessToken}}'
body:
  type: json
  content: |-
    {
      "name": "Example Product",
      "sku": "EX-SKU-001",
      "category": 1,
      "brand": 1
    }
