# Generated by Django 6.0.2 on 2026-02-21 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="name")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                ("is_active", models.BooleanField(default=True, verbose_name="is active")),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("code", models.CharField(max_length=50, unique=True, verbose_name="code")),
                ("location", models.CharField(max_length=255, verbose_name="location")),
            ],
            options={
                "verbose_name": "warehouse",
                "verbose_name_plural": "warehouses",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("sku", models.CharField(max_length=100, unique=True, verbose_name="sku")),
                ("product_type", models.CharField(max_length=100, verbose_name="product type")),
                ("cost_price", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="cost price")),
                ("selling_price", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="selling price")),
                ("is_active", models.BooleanField(default=True, verbose_name="is active")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="inventory.category",
                        verbose_name="category",
                    ),
                ),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "products",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StockTransfer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=14, verbose_name="quantity")),
                ("reference", models.CharField(blank=True, max_length=100, verbose_name="reference")),
                ("transferred_at", models.DateTimeField(auto_now_add=True, verbose_name="transferred at")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_transfers",
                        to="inventory.product",
                        verbose_name="product",
                    ),
                ),
                (
                    "from_warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_transfers",
                        to="inventory.warehouse",
                        verbose_name="from warehouse",
                    ),
                ),
                (
                    "to_warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_transfers",
                        to="inventory.warehouse",
                        verbose_name="to warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "stock transfer",
                "verbose_name_plural": "stock transfers",
                "ordering": ["-transferred_at"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "movement_type",
                    models.CharField(
                        choices=[("IN", "In"), ("OUT", "Out"), ("TRANSFER", "Transfer"), ("ADJUSTMENT", "Adjustment")],
                        max_length=20,
                        verbose_name="movement type",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=14, verbose_name="quantity")),
                ("reference", models.CharField(blank=True, max_length=100, verbose_name="reference")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("moved_at", models.DateTimeField(auto_now_add=True, verbose_name="moved at")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="inventory.product",
                        verbose_name="product",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="inventory.warehouse",
                        verbose_name="warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "stock movement",
                "verbose_name_plural": "stock movements",
                "ordering": ["-moved_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseReceipt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reference", models.CharField(max_length=100, unique=True, verbose_name="reference")),
                ("received_at", models.DateTimeField(auto_now_add=True, verbose_name="received at")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_receipts",
                        to="inventory.warehouse",
                        verbose_name="warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "purchase receipt",
                "verbose_name_plural": "purchase receipts",
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="Adjustment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity_delta", models.DecimalField(decimal_places=3, max_digits=14, verbose_name="quantity delta")),
                ("reason", models.CharField(blank=True, max_length=255, verbose_name="reason")),
                ("adjusted_at", models.DateTimeField(auto_now_add=True, verbose_name="adjusted at")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="inventory.product",
                        verbose_name="product",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="inventory.warehouse",
                        verbose_name="warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "adjustment",
                "verbose_name_plural": "adjustments",
                "ordering": ["-adjusted_at"],
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name="quantity")),
                (
                    "reserved_quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name="reserved quantity"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="inventory.product",
                        verbose_name="product",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="inventory.warehouse",
                        verbose_name="warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "stock",
                "verbose_name_plural": "stocks",
                "constraints": [
                    models.UniqueConstraint(fields=("product", "warehouse"), name="uq_stock_product_warehouse")
                ],
            },
        ),
    ]
