# Generated by Django 6.0.2 on 2026-04-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legal_trade_name", models.CharField(max_length=255)),
                ("trade_license_number", models.CharField(max_length=100)),
                (
                    "tax_registration_number",
                    models.CharField(blank=True, max_length=100),
                ),
                ("address", models.TextField()),
                ("phone_number", models.CharField(max_length=30)),
                ("email_address", models.EmailField(max_length=254)),
                ("bank_name_branch", models.CharField(blank=True, max_length=255)),
                ("iban", models.CharField(blank=True, max_length=34)),
                ("swift_bic_code", models.CharField(blank=True, max_length=11)),
                ("business_activity", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(default="active", max_length=20)),
            ],
            options={
                "ordering": ["legal_trade_name"],
            },
        ),
    ]
