# Generated by Django 6.0.2 on 2026-02-23 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, unique=True, verbose_name="name"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
            ],
            options={
                "verbose_name": "attribute",
                "verbose_name_plural": "attributes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, unique=True, verbose_name="name"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
            ],
            options={
                "verbose_name": "brand",
                "verbose_name_plural": "brands",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, unique=True, verbose_name="name"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
            ],
            options={
                "verbose_name": "material",
                "verbose_name_plural": "materials",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="adjustment",
            name="product",
        ),
        migrations.RemoveField(
            model_name="adjustment",
            name="warehouse",
        ),
        migrations.RemoveField(
            model_name="purchasereceipt",
            name="warehouse",
        ),
        migrations.RemoveConstraint(
            model_name="stock",
            name="uq_stock_product_warehouse",
        ),
        migrations.RemoveField(
            model_name="stockmovement",
            name="product",
        ),
        migrations.RemoveField(
            model_name="stockmovement",
            name="warehouse",
        ),
        migrations.RemoveField(
            model_name="stocktransfer",
            name="from_warehouse",
        ),
        migrations.RemoveField(
            model_name="stocktransfer",
            name="product",
        ),
        migrations.RemoveField(
            model_name="stocktransfer",
            name="to_warehouse",
        ),
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=120, unique=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="product",
            name="attributes",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="inventory.attribute",
                verbose_name="attributes",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="inventory.brand",
                verbose_name="brand",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="inventory.material",
                verbose_name="material",
            ),
        ),
        migrations.DeleteModel(
            name="Adjustment",
        ),
        migrations.DeleteModel(
            name="PurchaseReceipt",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="product",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="warehouse",
        ),
        migrations.DeleteModel(
            name="StockMovement",
        ),
        migrations.DeleteModel(
            name="StockTransfer",
        ),
        migrations.DeleteModel(
            name="Stock",
        ),
        migrations.DeleteModel(
            name="Warehouse",
        ),
    ]
