# Generated by Django 6.0.2 on 2026-04-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="email_address",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="phone_number",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="status",
            field=models.CharField(blank=True, default="active", max_length=20),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="trade_license_number",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
