# Generated by Django 6.0.2 on 2026-04-11 06:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_purchaseorder_vendor_help_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['trade_name'], 'verbose_name': 'vendor', 'verbose_name_plural': 'vendors'},
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='bank_name_branch',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='business_activity',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='legal_trade_name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='swift_bic_code',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='tax_registration_number',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='trade_license_number',
        ),
        migrations.AddField(
            model_name='vendor',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='account number'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='authorized_signatory',
            field=models.CharField(blank=True, max_length=255, verbose_name='authorized signatory'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='bank name'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='building_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='building name'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='city_emirate',
            field=models.CharField(blank=True, max_length=100, verbose_name='city / emirate'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='credit limit (AED)'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='credit_period',
            field=models.CharField(blank=True, max_length=100, verbose_name='credit period'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='license_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='license expiry'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='license_no',
            field=models.CharField(default='', max_length=100, verbose_name='trade license no'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='office_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='office phone'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100, verbose_name='payment method'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='phone',
            field=models.CharField(default='', max_length=30, verbose_name='phone (mobile)'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='power_of_attorney',
            field=models.FileField(blank=True, upload_to='inventory/vendors/poa/', verbose_name='power of attorney'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='primary_activity',
            field=models.CharField(blank=True, max_length=255, verbose_name='primary activity'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='primary_contact_person',
            field=models.CharField(blank=True, max_length=255, verbose_name='primary contact person'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='store_office_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='store/office no'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='street_area',
            field=models.CharField(blank=True, max_length=255, verbose_name='street / area'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='swift_bic',
            field=models.CharField(blank=True, max_length=20, verbose_name='SWIFT / BIC'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='trade_license_pdf',
            field=models.FileField(default='', upload_to='inventory/vendors/licenses/', verbose_name='trade license PDF'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='trade_name',
            field=models.CharField(default='', max_length=255, verbose_name='trade name (legal)'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='trn_certificate',
            field=models.FileField(default='', upload_to='inventory/vendors/trn/', verbose_name='TRN certificate'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='trn_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='TRN number'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_type',
            field=models.CharField(default='local', max_length=100, verbose_name='vendor type'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='website',
            field=models.URLField(blank=True, verbose_name='website'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='iban',
            field=models.CharField(blank=True, max_length=34, verbose_name='IBAN'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='status',
            field=models.CharField(default='active', max_length=100, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='VendorContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('designation', models.CharField(blank=True, max_length=100, verbose_name='designation')),
                ('mobile', models.CharField(blank=True, max_length=30, verbose_name='mobile')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='inventory.vendor', verbose_name='vendor')),
            ],
            options={
                'verbose_name': 'vendor contact',
                'verbose_name_plural': 'vendor contacts',
            },
        ),
    ]
