# Generated by Django 6.0.2 on 2026-04-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_vendor_options_remove_vendor_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='license_no',
            field=models.CharField(max_length=100, verbose_name='trade license no'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='phone (mobile)'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='trade_license_pdf',
            field=models.FileField(upload_to='inventory/vendors/licenses/', verbose_name='trade license PDF'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='trade_name',
            field=models.CharField(max_length=255, verbose_name='trade name (legal)'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='trn_certificate',
            field=models.FileField(upload_to='inventory/vendors/trn/', verbose_name='TRN certificate'),
        ),
    ]
