# Generated by Django 6.0.2 on 2026-04-11 08:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0022_alter_vendor_license_no_alter_vendor_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaserequisition",
            name="job_order_ref",
            field=models.CharField(
                blank=True,
                help_text="Job order reference used for Rework requisitions.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="purchaserequisition",
            name="project_site",
            field=models.CharField(
                blank=True,
                help_text="Job/Project reference for Job or Rework requisitions.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="purchaserequisition",
            name="requisition_date",
            field=models.DateField(
                default=django.utils.timezone.localdate,
                help_text="The creation date of the requisition.",
            ),
        ),
        migrations.AddField(
            model_name="purchaserequisition",
            name="requisition_type",
            field=models.CharField(
                choices=[
                    ("Job", "Job (Project)"),
                    ("Rework", "Rework"),
                    ("Normal Stock", "Normal Stock"),
                ],
                default="Normal Stock",
                help_text="Requisition mode: Job (Project), Rework, or Normal Stock.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="purchaserequisitionlineitem",
            name="description",
            field=models.TextField(
                blank=True, help_text="Line item specific notes or description."
            ),
        ),
        migrations.AddField(
            model_name="purchaserequisitionlineitem",
            name="preferred_vendor",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional vendor suggestion for this item.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="preferred_line_items",
                to="inventory.vendor",
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequisition",
            name="delivery_location",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Main Store", "Main Store"),
                    ("Factory Store", "Factory Store"),
                    ("Direct to Site", "Direct to Site"),
                ],
                default="",
                help_text="Destination delivery location.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequisition",
            name="priority",
            field=models.CharField(
                choices=[("High", "High"), ("Medium", "Medium"), ("Low", "Low")],
                default="Medium",
                help_text="Priority level: High, Medium, or Low.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequisition",
            name="purchase_request_number",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Auto-generated unique purchase requisition number (MRF Number).",
                max_length=30,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequisition",
            name="status",
            field=models.CharField(
                default="Draft",
                help_text="Current status: Draft, Submitted for Approval, Approved, Rejected.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequisition",
            name="stock_reason_category",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Reason category for normal stock requisitions (e.g., Low Stock, Routine Replenishment).",
                max_length=150,
            ),
        ),
    ]
