# Generated by Django 6.0.2 on 2026-04-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0023_purchaserequisition_job_order_ref_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaserequisitionlineitem",
            name="description",
        ),
        migrations.RemoveField(
            model_name="purchaserequisitionlineitem",
            name="preferred_vendor",
        ),
        migrations.RemoveField(
            model_name="purchaserequisitionlineitem",
            name="product",
        ),
        migrations.AddField(
            model_name="purchaserequisitionlineitem",
            name="product_category",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="purchaserequisitionlineitem",
            name="product_code",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="purchaserequisitionlineitem",
            name="product_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="purchaserequisitionlineitem",
            name="unit",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="purchaserequisition",
            name="delivery_location",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Destination delivery location.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequisition",
            name="priority",
            field=models.CharField(
                default="Medium",
                help_text="Priority level: High, Medium, or Low.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequisition",
            name="requisition_type",
            field=models.CharField(
                default="Normal Stock",
                help_text="Requisition mode: Job (Project), Rework, or Normal Stock.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="account_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="account number"
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="authorized_signatory",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="authorized signatory",
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="bank_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="bank name"
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="building_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="building name"
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="city_emirate",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="city / emirate"
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="credit_limit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="credit limit (AED)",
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="credit_period",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="credit period"
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="iban",
            field=models.CharField(
                blank=True, max_length=34, null=True, verbose_name="IBAN"
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="license_no",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="trade license no"
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="office_phone",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="office phone"
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="payment_method",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="payment method"
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="phone",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="phone (mobile)"
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="power_of_attorney",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="inventory/vendors/poa/",
                verbose_name="power of attorney",
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="primary_activity",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="primary activity"
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="primary_contact_person",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="primary contact person",
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="status",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="status"
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="store_office_no",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="store/office no"
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="street_area",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="street / area"
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="swift_bic",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="SWIFT / BIC"
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="trade_license_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="inventory/vendors/licenses/",
                verbose_name="trade license PDF",
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="trade_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="trade name (legal)"
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="trn_certificate",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="inventory/vendors/trn/",
                verbose_name="TRN certificate",
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="trn_number",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="TRN number"
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="vendor_type",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="vendor type"
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="website",
            field=models.URLField(blank=True, null=True, verbose_name="website"),
        ),
        migrations.AlterField(
            model_name="vendorcontact",
            name="designation",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="designation"
            ),
        ),
        migrations.AlterField(
            model_name="vendorcontact",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="email"
            ),
        ),
        migrations.AlterField(
            model_name="vendorcontact",
            name="mobile",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="mobile"
            ),
        ),
        migrations.AlterField(
            model_name="vendorcontact",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="name"
            ),
        ),
    ]
