# Generated by Django 6.0.2 on 2026-04-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0024_remove_purchaserequisitionlineitem_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaserequisition",
            name="delivery_location",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Main Store", "Main Store"),
                    ("Factory Store", "Factory Store"),
                    ("Direct to Site", "Direct to Site"),
                ],
                default="",
                help_text="Destination delivery location.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequisition",
            name="priority",
            field=models.CharField(
                choices=[("High", "High"), ("Medium", "Medium"), ("Low", "Low")],
                default="Medium",
                help_text="Priority level: High, Medium, or Low.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequisition",
            name="requisition_type",
            field=models.CharField(
                choices=[
                    ("Job", "Job (Project)"),
                    ("Rework", "Rework"),
                    ("Normal Stock", "Normal Stock"),
                ],
                default="Normal Stock",
                help_text="Requisition mode: Job (Project), Rework, or Normal Stock.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequisition",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Submitted for Approval", "Submitted for Approval"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Draft",
                help_text="Current status: Draft, Submitted for Approval, Approved, Rejected.",
                max_length=50,
            ),
        ),
    ]
