# Generated by Django 6.0.2 on 2026-04-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0025_alter_purchaserequisition_delivery_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaserequisition",
            name="delivery_location",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Destination delivery location.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequisition",
            name="priority",
            field=models.CharField(
                default="Medium",
                help_text="Priority level: High, Medium, or Low.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequisition",
            name="requisition_type",
            field=models.CharField(
                default="Normal Stock",
                help_text="Requisition mode: Job (Project), Rework, or Normal Stock.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequisition",
            name="status",
            field=models.CharField(
                default="Draft",
                help_text="Current status: Draft, Submitted for Approval, Approved, Rejected.",
                max_length=50,
            ),
        ),
    ]
