# Generated by Django 6.0.2 on 2026-04-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0026_alter_purchaserequisition_delivery_location_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vendor",
            old_name="power_of_attorney",
            new_name="bank_documant",
        ),
        migrations.AlterField(
            model_name="vendor",
            name="bank_documant",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="inventory/vendors/poa/",
                verbose_name="bank document",
            ),
        ),
    ]
