# Generated by Django 6.0.2 on 2026-04-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0027_remove_vendor_power_of_attorney_vendor_bank_documant"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="category",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="category"
            ),
        ),
    ]
