# Generated by Django 6.0.2 on 2026-04-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0029_alter_vendor_website"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaserequisition",
            name="project_site",
        ),
        migrations.AddField(
            model_name="purchaserequisition",
            name="rework_notes",
            field=models.TextField(
                blank=True, help_text="Justification and notes for rework requisitions."
            ),
        ),
    ]
