# Generated by Django 6.0.2 on 2026-04-11 11:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0030_remove_purchaserequisition_project_site_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaserequisition",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="purchaserequisition",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_requisitions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequisition",
            name="delivery_location",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Destination delivery location.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequisition",
            name="is_approved",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="purchaserequisition",
            name="is_rejected",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="purchaserequisition",
            name="job_order_ref",
            field=models.CharField(
                blank=True,
                help_text="Job order reference used for Rework requisitions.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequisition",
            name="notes_to_purchase_team",
            field=models.TextField(
                blank=True,
                help_text="Specific instructions for the procurement department.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequisition",
            name="priority",
            field=models.CharField(
                blank=True,
                default="Medium",
                help_text="Priority level: High, Medium, or Low.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequisition",
            name="purchase_request_number",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Auto-generated unique purchase requisition number (MRF Number).",
                max_length=30,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequisition",
            name="reason_description",
            field=models.TextField(
                blank=True,
                help_text="Provide justification for this purchase requisition.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequisition",
            name="required_by_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="purchaserequisition",
            name="requisition_date",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.localdate,
                help_text="The creation date of the requisition.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequisition",
            name="requisition_type",
            field=models.CharField(
                blank=True,
                default="Normal Stock",
                help_text="Requisition mode: Job (Project), Rework, or Normal Stock.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequisition",
            name="rework_notes",
            field=models.TextField(
                blank=True,
                help_text="Justification and notes for rework requisitions.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequisition",
            name="status",
            field=models.CharField(
                blank=True,
                default="Draft",
                help_text="Current status: Draft, Submitted for Approval, Approved, Rejected.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequisition",
            name="stock_reason_category",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Reason category for normal stock requisitions (e.g., Low Stock, Routine Replenishment).",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequisition",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="purchaserequisitionlineitem",
            name="net_required_qty",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                editable=False,
                help_text="Net quantity needed after accounting for stock and pending orders.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequisitionlineitem",
            name="pending_po_qty",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Quantity in pending purchase orders.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequisitionlineitem",
            name="pending_pr_qty",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Quantity in other pending purchase requisitions.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequisitionlineitem",
            name="product_category",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="purchaserequisitionlineitem",
            name="product_code",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="purchaserequisitionlineitem",
            name="product_name",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="purchaserequisitionlineitem",
            name="purchase_requisition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_items",
                to="inventory.purchaserequisition",
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequisitionlineitem",
            name="requested_qty",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Quantity requested by the requester.",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequisitionlineitem",
            name="stock_on_hand",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Current stock level at time of PR creation.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequisitionlineitem",
            name="unit",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
    ]
