# Generated by Django 6.0.2 on 2026-04-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0031_alter_purchaserequisition_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="available",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="available",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="reserved",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="reserved",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="stock_on_hand",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="stock on hand",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="stock_value_aed",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=14,
                null=True,
                verbose_name="stock value (AED)",
            ),
        ),
    ]
