# Generated by Django 6.0.2 on 2026-04-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0032_product_available_product_reserved_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaserequisition",
            name="reject_note",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Reason for rejecting this purchase requisition.",
                null=True,
            ),
        ),
    ]
