# Generated by Django 6.0.2 on 2026-04-18 06:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0033_purchaserequisition_reject_note"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseorderlineitem",
            name="pr_line_item",
        ),
        migrations.RemoveField(
            model_name="purchaseorderlineitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="purchaseorderlineitem",
            name="qty",
        ),
        migrations.RemoveField(
            model_name="purchaseorderlineitem",
            name="required_by",
        ),
        migrations.AddField(
            model_name="purchaseorderlineitem",
            name="description",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorderlineitem",
            name="last_purchase_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Last purchase rate for this item.",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderlineitem",
            name="product_code",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorderlineitem",
            name="purchase_requisition",
            field=models.ForeignKey(
                blank=True,
                help_text="The purchase requisition associated with this PO line.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="po_line_items",
                to="inventory.purchaserequisition",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderlineitem",
            name="requested_qty",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Requested quantity.",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderlineitem",
            name="required_by_date",
            field=models.DateField(
                blank=True, help_text="Date by which this item is required.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderlineitem",
            name="delivery_location",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Delivery location for this line item.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderlineitem",
            name="unit",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
    ]
