# Generated by Django 6.0.2 on 2026-04-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0034_remove_purchaseorderlineitem_pr_line_item_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaserequisitionlineitem",
            name="product_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
