# Generated by Django 6.0.2 on 2026-02-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="company",
            name="company_com_code_59946e_idx",
        ),
        migrations.AlterField(
            model_name="company",
            name="code",
            field=models.CharField(max_length=50, unique=True, verbose_name="code"),
        ),
        migrations.AlterField(
            model_name="company",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="is active"),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=200, verbose_name="name"),
        ),
    ]
