# Generated by Django 6.0 on 2026-02-12 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_companyuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CompanyUser",
        ),
    ]
