# Generated by Django 6.0.2 on 2026-03-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0005_companyfeature"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="address",
            field=models.TextField(blank=True, default="", verbose_name="address"),
        ),
        migrations.AddField(
            model_name="company",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254, verbose_name="email address"),
        ),
        migrations.AddField(
            model_name="company",
            name="licence_number",
            field=models.CharField(blank=True, default="", max_length=100, verbose_name="licence number"),
        ),
        migrations.AddField(
            model_name="company",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="companies/logos/", verbose_name="company logo"),
        ),
        migrations.AddField(
            model_name="company",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=30, verbose_name="phone"),
        ),
        migrations.AddField(
            model_name="company",
            name="website",
            field=models.URLField(blank=True, default="", verbose_name="website"),
        ),
    ]
