# Generated by Django 6.0.2 on 2026-03-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0006_company_contact_details_and_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="trn",
            field=models.CharField(blank=True, default="", max_length=100, verbose_name="trn"),
        ),
    ]
