# Generated by Django 6.0.2 on 2026-03-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0007_company_trn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="website",
            field=models.CharField(blank=True, default="", max_length=500, verbose_name="website"),
        ),
    ]
