# Generated by Django 6.0.2 on 2026-04-02 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0008_alter_company_website"),
        ("navigation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyModule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="company.company"),
                ),
                (
                    "module",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="navigation.module"),
                ),
            ],
            options={
                "verbose_name": "company module",
                "verbose_name_plural": "company modules",
            },
        ),
        migrations.AddConstraint(
            model_name="companymodule",
            constraint=models.UniqueConstraint(
                fields=("company", "module"),
                name="unique_company_module_access",
            ),
        ),
    ]
