# Generated by Django 6.0.2 on 2026-03-28 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0002_rename_global_terms_to_term_condition"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TermCondition",
            new_name="TermsConditions",
        ),
        migrations.AlterField(
            model_name="termsconditions",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_terms_conditions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="approved by",
            ),
        ),
        migrations.AlterField(
            model_name="termsconditions",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_terms_conditions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
    ]
