# Generated by Django 6.0.2 on 2026-03-28 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0003_pluralize_term_condition_to_terms_conditions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="termsconditions",
            name="approved_at",
        ),
        migrations.RemoveField(
            model_name="termsconditions",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="termsconditions",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="termsconditions",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="termsconditions",
            name="is_approved",
        ),
        migrations.RemoveField(
            model_name="termsconditions",
            name="updated_at",
        ),
    ]
