# Generated by Django 6.0.2 on 2026-03-28 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0004_remove_audit_fields_from_terms_conditions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="termsconditions",
            name="is_default",
        ),
    ]
