# Generated by Django 6.0.2 on 2026-03-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0005_remove_is_default_from_terms_conditions"),
    ]

    operations = [
        migrations.AddField(
            model_name="termsconditions",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="is default"),
        ),
    ]
