# Generated by Django 6.0.2 on 2026-03-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LeadManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(max_length=150, verbose_name="contact name"),
                ),
                ("company", models.CharField(max_length=150, verbose_name="company")),
                (
                    "email_address",
                    models.EmailField(max_length=254, verbose_name="email address"),
                ),
                ("phone", models.CharField(max_length=30, verbose_name="phone")),
                (
                    "lead_source",
                    models.CharField(max_length=150, verbose_name="lead source"),
                ),
            ],
        ),
    ]
