# Generated by Django 6.0.2 on 2026-03-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=150, verbose_name="customer name"),
                ),
                (
                    "email_address",
                    models.EmailField(max_length=254, verbose_name="email address"),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="company name"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=30, verbose_name="phone number"),
                ),
            ],
        ),
    ]
