# Generated by Django 6.0.2 on 2026-03-17 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_name",
                    models.CharField(max_length=200, verbose_name="project name"),
                ),
                (
                    "new_client_name",
                    models.CharField(blank=True, max_length=200, verbose_name="new client name"),
                ),
                (
                    "project_description",
                    models.TextField(blank=True, verbose_name="project description"),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=200, verbose_name="location"),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        upload_to="crm/enquiries/",
                        verbose_name="attachment",
                    ),
                ),
                (
                    "existing_client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enquiries",
                        to="crm.customer",
                        verbose_name="existing client",
                    ),
                ),
            ],
        ),
    ]
