# Generated by Django 6.0.2 on 2026-03-17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_enquiry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="enquiry",
            name="email_address",
            field=models.EmailField(blank=True, default="", max_length=254, verbose_name="email address"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="enquiry",
            name="company_name",
            field=models.CharField(blank=True, default="", max_length=200, verbose_name="company name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="enquiry",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=30, verbose_name="phone number"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="enquiry",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=timezone.now, verbose_name="created at"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="enquiry",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=timezone.now, verbose_name="updated at"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="enquiry",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_enquiries",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_enquiries",
                to=settings.AUTH_USER_MODEL,
                verbose_name="updated by",
            ),
        ),
    ]
