# Generated by Django 6.0.2 on 2026-03-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_customer_lead_audit_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="enquiry",
            name="status",
            field=models.CharField(default="Awaiting BOQ", max_length=50, verbose_name="status"),
        ),
    ]
