# Generated by Django 6.0.2 on 2026-03-17

import uuid
from django.db import migrations, models


def backfill_enquiry_codes(apps, schema_editor):
    Enquiry = apps.get_model("crm", "Enquiry")
    db_alias = schema_editor.connection.alias

    existing = set(
        Enquiry.objects.using(db_alias)
        .exclude(enquiry_code__isnull=True)
        .exclude(enquiry_code="")
        .values_list("enquiry_code", flat=True)
    )

    for enquiry in Enquiry.objects.using(db_alias).filter(enquiry_code__isnull=True):
        code = None
        while not code or code in existing:
            code = f"ENQ-{str(uuid.uuid4())[:6].upper()}"
        enquiry.enquiry_code = code
        enquiry.save(update_fields=["enquiry_code"])
        existing.add(code)


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0006_enquiry_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="enquiry",
            name="enquiry_code",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="enquiry code",
            ),
        ),
        migrations.RunPython(backfill_enquiry_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="enquiry",
            name="enquiry_code",
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name="enquiry code"),
        ),
    ]
