# Generated by Django 6.0.2 on 2026-03-18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0007_enquiry_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="enquiry",
            old_name="status",
            new_name="boq_status",
        ),
    ]
