# Generated by Django 6.0.2 on 2026-03-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0008_rename_status_to_boq_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="enquiry",
            name="quote_status",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="quote status",
            ),
        ),
    ]
