# Generated by Django 6.0.2 on 2026-03-23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0009_enquiry_quote_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enquiry",
            name="quote_status",
        ),
    ]
