# Generated by Django 6.0.2 on 2026-03-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0010_rename_boq_status_remove_quote_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadmanagement",
            name="requirment",
            field=models.TextField(blank=True, default="", verbose_name="requirment"),
        ),
    ]
