# Generated by Django 6.0.2 on 2026-03-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0011_leadmanagement_requirment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enquiry",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "enquiry",
                "verbose_name_plural": "enquiries",
            },
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="status",
            field=models.CharField(
                default="Awaiting Bill of Quantity",
                max_length=50,
                verbose_name="status",
            ),
        ),
    ]
