# Generated by Django 6.0.2 on 2026-03-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0012_alter_enquiry_options_alter_enquiry_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="enquiry",
            name="trn",
            field=models.CharField(blank=True, max_length=100, verbose_name="trn"),
        ),
    ]
