# Generated by Django 6.0.2 on 2026-03-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0013_enquiry_trn"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="trn",
            field=models.CharField(blank=True, max_length=100, verbose_name="trn"),
        ),
    ]
