# Generated by Django 6.0.2 on 2026-04-09 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0014_customer_trn"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LeadManagement",
        ),
    ]
