# Generated by Django 6.0.2 on 2026-04-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0015_delete_leadmanagement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquiry",
            name="status",
            field=models.CharField(
                default="pending", max_length=50, verbose_name="status"
            ),
        ),
    ]
